# Generated by Django 5.0.6 on 2025-04-06 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_devnagiri', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('caste_category', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('tehsil_taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('ews_certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ews_issuing_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('ews_date_of_issue', models.DateField(blank=True, null=True)),
                ('ews_validity_period', models.DateField(blank=True, null=True)),
                ('ews_family_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ews_family_assets', models.TextField(blank=True, null=True)),
                ('ews_certificate_document', models.FileField(blank=True, null=True, upload_to='documents/ews/')),
                ('caste_certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('caste_issuing_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('caste_date_of_issue', models.DateField(blank=True, null=True)),
                ('caste_validity_period', models.DateField(blank=True, null=True)),
                ('caste_certificate_document', models.FileField(blank=True, null=True, upload_to='documents/caste/')),
                ('income_certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('income_issuing_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('income_date_of_issue', models.DateField(blank=True, null=True)),
                ('income_validity_period', models.DateField(blank=True, null=True)),
                ('annual_family_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('income_certificate_document', models.FileField(blank=True, null=True, upload_to='documents/income/')),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_passing', models.IntegerField(null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('marksheet_document', models.FileField(blank=True, null=True, upload_to='documents/marksheet/')),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(max_length=50)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('expected_json', models.JSONField(blank=True, null=True)),
                ('mismatches', models.JSONField(blank=True, null=True)),
                ('mismatch_percentage', models.FloatField(blank=True, null=True)),
                ('mismatch_plot_path', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rac_idp.applicant')),
            ],
        ),
    ]
