# Generated by Django 5.0.6 on 2025-04-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_idp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationresult',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar'), ('marksheet', 'Marksheet'), ('ews', 'EWS Certificate'), ('income', 'Income Certificate'), ('caste', 'Caste Certificate')], max_length=50),
        ),
    ]
