# Generated by Django 5.0.6 on 2025-03-22 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('caste_category', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('ews_certificate', models.FileField(blank=True, null=True, upload_to='documents/ews/')),
                ('caste_certificate', models.FileField(blank=True, null=True, upload_to='documents/caste/')),
                ('income_certificate', models.FileField(blank=True, null=True, upload_to='documents/income/')),
                ('marksheet_document', models.FileField(blank=True, null=True, upload_to='documents/marksheet/')),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_passing', models.IntegerField(null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('experience_certificate', models.FileField(blank=True, null=True, upload_to='documents/experience/')),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('expected_json', models.JSONField(blank=True, null=True)),
                ('mismatches', models.JSONField(blank=True, null=True)),
                ('mismatch_percentage', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('mismatch_plot_path', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rac_idp.applicant')),
            ],
        ),
    ]
