# Generated by Django 5.1.6 on 2025-02-16 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_idp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='extracted_data',
            new_name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='applicant',
            name='form_data',
            field=models.JSONField(default='NA'),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='mismatches',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rac_idp.applicant'),
        ),
    ]
