# Generated by Django 5.0.6 on 2025-03-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_idp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationresult',
            name='mismatch_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationresult',
            name='mismatches',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
