# Generated by Django 5.0.6 on 2025-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_idp', '0002_rename_extracted_data_document_extracted_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
