# Generated by Django 5.0.6 on 2025-03-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rac_idp', '0002_applicationresult_mismatch_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='caste_certificate',
            new_name='caste_certificate_document',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='ews_certificate',
            new_name='ews_certificate_document',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='income_certificate',
            new_name='income_certificate_document',
        ),
    ]
