# Generated by Django 5.0.6 on 2025-03-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rac_idp', '0002_alter_applicant_user_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
    ]
