# Generated by Django 5.0.6 on 2025-02-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_idp', '0003_alter_applicant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='form_data',
        ),
        migrations.AddField(
            model_name='applicant',
            name='expected_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='extracted_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mismatches',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
