# Generated by Django 5.0.6 on 2025-02-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rac_idp', '0004_remove_applicant_form_data_applicant_expected_json_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='extracted_json',
            new_name='extracted_data',
        ),
    ]
