# Generated by Django 5.0.6 on 2025-03-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_idp', '0005_alter_applicant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationresult',
            name='mismatch_percentage',
            field=models.FloatField(null=True),
        ),
    ]
