# Generated by Django 5.0.6 on 2025-02-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_idp', '0005_rename_extracted_json_applicant_extracted_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='mismatch_percentage',
            field=models.FloatField(default=0),
        ),
    ]
